// src/components/coursePage/FetchQueue.jsx
import {Component} from "react"
import {konsole} from "../fn"
import QueueInfo, {initialQiData} from "./QueueInfo"
/**
 * 
 * props : section , sidx, prefixCls
 * */
class FetchQueue extends Component{
	prefixCls = null
	constructor(props){
		super(props)
		const {section, sidx,tidx, prefixCls} = props
		this.prefixCls = prefixCls || 'fetch-queue'
		this.state = {
			btnState : 1,
			hideProgress : false,
			hideBtn : false,
			percentage : 0,
			qiData : initialQiData,
			queueStarted : false	
		}
	}
	
	
	startQueue(){
		konsole.log(`FetchQueueBar.startQueue() sidx=${sidx} sidx=${tidx}`)
	}

	render(){
		const {btnState, hideProgress, percentage, hideBtn,qiData, queueStarted} = this.state
		
		const iconCls = btnState === 1 ? 'fa-play'
				   : btnState === 2 ? 'fa-spin fa-spinner' 
				   					: btnState === 3 ? 'fa-check' 
				   									 : btnState === 4 ? 'fa-refresh' 
				   									 				  : 'fa-play'
		const {prefixCls} = this    									 				  
		return(<> <div className={`${prefixCls}-bar`} style={style.qcnt}>
	        <div className={`${prefixCls}-pb item`} style={{width:100}}>
	        	{
	        		!hideProgress ? (<div className="progress">
		                <div className="progress-bar bg-info" 
		                	 role="progressbar" 
		                	 style={{width : `${percentage}%`}} 
		                	 aria-valuenow={percentage} 
		                	 aria-valuemin={0} 
		                	 aria-valuemax={100}>
		                </div>
		            </div>) : ""
	        	}
	        </div>
	        {
	        	!hideBtn ? (<div className={`btn-${prefixCls}-cnt item`} style={{position:'absolute'}}>
		            <button style={Object.assign({ color : btnState === 3 ? 'white' : 'inherit' },style.btnFetch)} 
		            		disabled={btnState !==1 && btnState !== 4} 
		            		onClick={e => this.startQueue()} 
		            		className={`btn btn-sm btn-${prefixCls}`}>
		            	<i className={`fa ${iconCls}`}></i></button>
		            	{
		            		queueStarted ? (<QueueInfo data={qiData}/>):""
		            	}
		            	
		        </div>) : ""
	        }
	        
	    </div></>)		   									 				  
	}
	
}

const style={
	qcnt : {
		display : 'flex',
		justifyContent : 'end'
	},
	item:{
		display:'block',
		border:'solid 1px #ddd'
	},
	btnFetch:{
		padding: 0,
	    marginTop: '-10px',
	    fontSize: '70%',
	    marginRight: '4px',
	    border:'none',
	    color:'#333'

	}
}
export default FetchQueue

// src/popup/components/FetchQueue.vue
<template>
    <div class="fetch-queue">
        <div style="width:90%;height:15px">
            <div class="progress" v-show="percentage > 0">
                <div class="progress-bar" role="progressbar" :style="{width:percentage+'%'}" :aria-valuenow="percentage" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div class="btn-fetch-cnt">
            <button :disabled="btnState!=1&&btnState!=4" @click="startQueue()" class="btn btn-sm btn-fetch"><i class="fa" :class="{'fa-play':btnState==1,'fa-spin fa-spinner':btnState==2,'fa-check':btnState==3,'fa-refresh':btnState==4}"></i></button>
        </div>
    </div>
</template>

<script lang="ts">
import {defineComponent,ref} from 'vue'
export default defineComponent({
  props:{

  },
  setup(props){
    let queueSlugs = ref([]);
    let excludeSlugs = ref([]);
    let percentage = ref(0);
    let btnState = ref(1);
    let lastTocIndex = ref(0);
    return {queueSlugs,excludeSlugs,percentage,btnState,lastTocIndex};
  },
  methods:{
    setProgress(lastTocIndex:number,percentage:number){
        this.lastTocIndex = lastTocIndex;
        this.percentage = percentage;
        if(percentage==100){
            this.btnState = 3;
        }
        console.log(percentage)
    },
    startQueue(){
        this.percentage = this.percentage==0?1:this.percentage;
        this.btnState = 2;
        this.$parent.triggerFetchQueue(this.lastTocIndex==0?-1:this.lastTocIndex);
    }
  }
});
</script>
<style scoped>
.btn-fetch{
    margin-top:-8px;
    padding:0;
    border:none !important;
}
.fetch-queue{
    margin-bottom: 1em;
}
.btn-fetch-cnt{
    width: 25px;
    position: absolute;
    right: 90px;
    margin-top: -18px;
}
</style>
