// src/popup/components/PageNavigation.vue
<template>
  <div class="page-navigation text-center">
    <ul class="btn-group">
        <li @click="onNavClick('welcome')" class="btn btn-sm btn-primary" :class="{active : nav=='welcome'}">Welcome</li>
        <li @click="onNavClick('course')" class="btn btn-sm btn-primary" :class="{active : nav=='course'}">Course</li>
        <li @click="onNavClick('downloads')" class="btn btn-sm btn-primary" :class="{active : nav=='downloads'}">Downloads</li>
        <li v-if="0" @click="onNavClick('help')" class="btn btn-sm btn-primary" :class="{active : nav=='help'}">Help</li>
        <li v-if="0" @click="onNavClick('about')" class="btn btn-sm btn-primary" :class="{active : nav=='about'}">About</li>
    </ul>
  </div>
</template>
<script lang="ts">
import { defineComponent, ref, PropType } from 'vue'
import NavTerm from '../../types/navterm';
export default defineComponent({
  props:{
    nav :{
        required:true,
        type: String as PropType<NavTerm>
    }
  },  
  setup(props) {
    const nav = ref(props.nav);

    return {nav};
  },
  methods:{
    onNavClick(target : NavTerm){
        console.log(target);
        this.nav = target;
        this.$emit('update', target);
    }
  }
})
</script>

// src/components/PageNavigation.jsx

import {useState, useEffect} from "react"

const PageNavigation = ({onNavUpdate}) => {
	const [activeNav, setActiveNav] = useState('welcome')
	const [enableOption, setEnableOption] = useState(false)
	const btnCls = "btn btn-sm btn-primary"

	const onNavClick = (navName) => {
		setActiveNav(navName)
		onNavUpdate(navName)
	}

	const getBtnCls = navName => {

	}

	return(<div className="page-navigation text-center">
	    <ul className="btn-group">
	        <li> <a href="#" onClick={evt => onNavClick('welcome')} className={getBtnCls('welcome')}>Welcome</a></li>
	        <li> <a href="#" onClick={evt => onNavClick('course')} className={getBtnCls('course')}>Course</a></li>
	        <li> <a href="#" onClick={evt => onNavClick('download')} className={getBtnCls('download')}>Downloads</a></li>
	        {
	        	enableOption ? (<li> <a href="#" onClick={evt = onNavClick('option')} className={getBtnCls('option')}>Option</a></li>
	        	):""
	        }
	        <li> <a href="#" onClick={evt => onNavClick('setting')} className={getBtnCls('setting')}>Setting</a></li>
	        
	    </ul>
  	</div>)
}

export default PageNavigation
