// src/popup/views/WelcomePage.vue
<template>
  <div class="welcome-page page">
    <p class="text-center">{{greeting}}</p>
    <div class="action-cnt">
      <div class="dropdown" v-if="lastCourseList.length>0">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="recentCourseButton" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-history"></i> Load Recent Course
        </button>
        <ul class="dropdown-menu" aria-labelledby="recentCourseButton">
          <li :key="course.ID" v-for="course in lastCourseList"><a class="dropdown-item" href="javascript:;" @click="loadRecentCourse(course)">{{ course.title }}</a></li>
        </ul>
      </div>

      <div class="btn-cnt">
        <button :disabled="fetchBtnState==1" class="btn btn-primary" @click="retrieveDataCodesFromContent()"><i class="fa" :class="{'fa-hand-o-right':fetchBtnState==0,'fa-spin fa-spinner':fetchBtnState==1,'fa-refresh':fetchBtnState==2}"></i> Fetch This Course</button>
      </div>

    </div>
  </div>
</template>
<script lang="ts">
import { sendMessageSaveDataCodesToLS } from 'src/libs/utils';
import { ComponentPublicInstance, defineComponent,ref } from 'vue';
import Store from 'src/libs/store';
import { Course_tableField } from 'src/types/tableFields';
import CoursePage from 'src/popup/views/CoursePage.vue';

export default defineComponent({
  setup() {
    const nav = ref('welcome');
    const greeting = ref('Welcome to LLFetcher 1.0.1, what do you want to do ?');
    const lastCourseList = ref<Course_tableField[]>([]);
    const fetchBtnState = ref(0);
    return {
      nav,greeting,lastCourseList,fetchBtnState
    }
  },
  mounted(){
    setTimeout(()=>{
      const appInfo = Store.getAppInfo();
      // this.$parent.log(`AppState:${appInfo.state}`);
      
      const lastCourses = Store.getLastCourses();
      if(lastCourses.length > 0){
        this.lastCourseList = [];
        lastCourses.map((course:Course_tableField)=>{
            this.lastCourseList.push(course);
        });
      }
      
    },1259);

  },
  methods:{
    loadRecentCourse(course:Course_tableField){
      const parent = this.$parent as ComponentPublicInstance<typeof CoursePage>;
      parent.setCourse(course);
    },
    retrieveDataCodesFromContent(){
      this.fetchBtnState = 1;
      // send data code from content script to LS
      sendMessageSaveDataCodesToLS();
      // load data codes from ls
      Store.getDataCodesLS((dataCodes)=>{

        this.fetchBtnState = 2;
        console.log(dataCodes)
        Store.saveDataCodes(dataCodes);
        const parent = this.$parent as ComponentPublicInstance<typeof CoursePage>;
        parent.setCourse(dataCodes.course);
        // contentConsoleLog(dataCodes);
      })

    }
  }
})
</script>

// src/components/WelcomePage.jsx
import  {
	titleCase
} from "./fn"

import App  from "../models/App"
import Course  from "../models/Course"
import Author  from "../models/Author"
import BasicPageWithMessaging from "./BasicPageWithMessaging"

let onMessageAttached = false

const mApp = await App.getInstance()
const mCourse = await Course.getInstance()
const mAuthor = await Author.getInstance()


class WelcomePage extends BasicPageWithMessaging {
	courseAuthors = []
	constructor(props){
		super(props)
		this.state = {
			greeting : 'Welcome to LLFetcher 2.0',
			lastCourseList : {},
			fetchBtnState : 0,
			loading : false,
			courseInfo : null,
			validCoursePage : false,
			disableFetchBtn:false
		}
	}



	async addToLastCourseList(ci){
		this.setState({courseInfo:ci})
		const slug = ci.slug
		const course = await this.createCourse(ci)
		if(!Object.keys(this.state.lastCourseList).includes(slug)){
			this.populateLastCourseList()
		}
		await this.props.onSelectCourse(course, this.courseAuthors)

	}
	async createAuthors(authors, course){
		// const courseAuthorsTmp = []
		for(let i in authors){
			const {slug,biography,shortBiography} = authors[i]
			const name = titleCase(slug)
			const author = await mAuthor.create(name,slug,biography,shortBiography,course.id)
			// console.log(author)
			if(this.courseAuthors.filter(_author_ => _author_.id === author.id).length === 0){
				this.courseAuthors.push(author)
				course = await mCourse.addAuthorId(course.id, author.id)
			}
			
		}

		return course

	}

	async createCourse(ci){
		// insert course
		const {title,slug,duration,sourceCodeRepository,description,urn} = ci
		let course = await mCourse.create(title,slug,duration,sourceCodeRepository,description,urn)
		console.log(course)
		
		course = await this.createAuthors(ci.authors, course)
		return course
	}



	onMessageCommand(evt, source){
		if(evt.name === 'cmd.validCoursePageAuto'){
    		this.setState({validCoursePage:evt.data})
		}
	}

	populateLastCourseList(){
		const savedCourseList = mCourse.getList()
		let courseListObj = {}
		for(let i in savedCourseList){
			courseListObj[savedCourseList[i].slug] = savedCourseList[i]
		} 
		this.setState({lastCourseList :courseListObj})

	}
	
	async componentDidMount(){
		this.populateLastCourseList() 
		this.initMessaging()
		await this.getValidCourseMessage()

	}
	async getValidCourseMessage(){
		const msg = 'cmd.validCoursePage'
		const validCoursePage = await this.getFromMessage(msg)
		this.setState({validCoursePage})
	}
	async getCourseInfoMessage(){
		const msg = 'cmd.getCourseInfo'
		this.setState({fetchBtnState:1})

		const course = await this.getFromMessage(msg)
		await this.addToLastCourseList(course)
	}
	
	async onSelectCourse(course){
	 	this.setState({loading:true, disableFetchBtn:true})
		await this.props.onSelectCourse(course,null,true)
		this.setState({loading:false, disableFetchBtn:false})
	}
	render(){
		const {greeting,lastCourseList,fetchBtnState,validCoursePage, loading, disableFetchBtn} = this.state
		const lastCourseListKeys = Object.keys(lastCourseList)
		const btnCls = fetchBtnState==0 ? 'fa-hand-o-right': fetchBtnState==1 ? 'fa-spin fa-spinner' : fetchBtnState==2 ? 'fa-refresh' : 'fa-hand-o-right'

		return(<>
			<div className="welcome-page page">
				<p className="text-center" style={{fontFamily:"Monoton, cursive"}}>{greeting}</p>
				<div className="action-cnt">
				{
					lastCourseListKeys.length > 0 ? (<>
						<div className="dropdown">
							<button disabled={loading} className="btn btn-secondary dropdown-toggle" type="button" id="recentCourseButton" data-bs-toggle="dropdown" aria-expanded="false">
							<i className={loading?"fa fa-spin fa-spinner":"fa fa-history"}></i> Load Recent Course
							</button>
							<ul className="dropdown-menu" aria-labelledby="recentCourseButton">
							{
								lastCourseListKeys.map((slug,index)=>{
									const course = lastCourseList[slug]
									return (<li key={index}>
										<a className="dropdown-item" href="#" onClick={e => this.onSelectCourse(course)}>{ course.title }</a>
										</li>)
								})	
							
							}
							</ul>
						</div>
					</>) : ""
				}
				

				<div className="btn-cnt">
					<button  disabled={fetchBtnState==1 || !validCoursePage || disableFetchBtn} className="btn btn-primary" onClick={e => this.getCourseInfoMessage()}><i className={`fa ${btnCls}`}></i> Fetch This Course</button>
					{/* <span>Valid CoursePage ? {validCoursePage ? 'Yes' : 'No'}</span> */}
				</div>

				</div>
			</div>
	</>)
	}
    
}


export default WelcomePage
