// src/option-page/components/coursePage/FetchButton.jsx
import {Component} from "react"
// import ComponentWithMessaging from "../ComponentWithMessaging"
 
import {parseToc} from "../learning_fn"

class FetchButton extends Component{
	course = null
	mCourse = null 
	mExfile = null 
	mToc = null 
	mStreamloc = null 

	constructor(props){
		super(props)
		const {store} = props
		this.store = store
		this.course = props.course

		this.mCourse = store.get('Course') 
		this.mExfile = store.get('ExerciseFile') 
		this.mToc = store.get('Toc') 
		this.mStreamloc = store.get('StreamLocation')

		this.state = {
			btnState : 0,
			toc : props.toc	,
			exerciseFile : null, 
			streamlocs : []
		}
	}
	
	async fetchToc() {
		console.log(this.state.toc)
		const url =  `https://www.linkedin.com/learning/${this.course.slug}/${this.state.toc.slug}`;
		this.setState({btnState:2})
		const [validResource, tocUp, exFile, streamLocations] = await this.getCourseTocMessage(url)
		console.log([validResource, tocUp, exFile, streamLocations])
		const btnState = validResource ? 3 : 4

		if(validResource){
			tocUp.url = url
			const records = await this.saveRecords(tocUp, exFile, streamLocations)

			console.log(records)

		}
		this.setState({btnState})

		return validResource
		
	}
	async saveRecords(tocUp, exFile, streamLocations){
		// store exercise file
		const {name,sizeInBytes} = exFile
		const exerciseFile = await this.mExfile.create(name,exFile.url,sizeInBytes,this.course.id)
		// store streamlocations
		
		const streamlocIds = []
		const streamlocs = []

		for(let i in streamLocations){
			const {fmt, url} = streamLocations[i]
			const streamloc = await this.mStreamloc.create(fmt, url, this.state.toc.id)
			streamlocIds.push(streamloc.id)
			streamlocs.push(streamloc)
		}

		// update toc , with streamlocation ids
		const {captionUrl, captionFmt} = tocUp
		const toc = await this.mToc.update(this.state.toc.id,tocUp.url, captionUrl, captionFmt, streamlocIds)

		this.setState({toc,  exerciseFile, streamlocs})
		return [toc, exerciseFile, streamlocs]

	}
	async getCourseTocMessage(url){
		return this.getCourseToc(url)
		// const msg = 'cmd.getCourseToc'
		// const results = await this.getFromMessage(msg, url)
		// return results
		// console.log(results)
	}
	async loadCourseToc(){
		const toc = this.mToc.get(this.state.toc.id)
		const exerciseFile = this.mExfile.getByCourseId(this.course.id)
		const streamlocs = this.mStreamloc.getListByTocId(this.state.toc.id)

		this.setState({toc,  exerciseFile, streamlocs})

	}

	isFetched(){
		return this.state.streamlocs.length > 0
	}
	async componentDidMount(){
		await this.loadCourseToc()
		if(this.state.toc.streamLocationIds.length > 0){
			this.setState({btnState:3})
		}
	}
	async getCourseToc(url){
		// console.log(toc.url)
		let resultCode = 4
		try{
			const res = await fetch(`${url}?rand=${(new Date).getTime()}`)
			const text= await res.text()
			resultCode = 3
			const parsed = parseToc(text)
			console.log(parsed)
			return parsed
		}catch(e){
			console.log(e)

		}
	}
	render(){

		const {toc} = this.state
		const {btnState} = this.state
		const btnStateNotLoading = btnState !== 1 && btnState !== 4
		const btnStyle = { border : ( btnStateNotLoading ? 'none' : 'inherit') }
		const iconCls = btnState === 1 ? 'fa-play' 
			   : btnState === 2 ? 'fa-spin fa-spinner' 
			   					: btnState === 3 ? 'fa-check' 
		   									 : btnState === 4 ? 'fa-refresh'
		   									 				  : 'fa-play'
		return(<><div className="btn-group">
		    <button style={btnStyle} 
		    		disabled={btnState > 1 && btnState < 4} 
		    		onClick={e => this.fetchToc()} 
		    		className="text-xss" 
		    		title={`Click to fetch TOC resources ${toc.title}`}>
		      	<i className={"fa " + iconCls}></i>
		    </button>
	  	</div></>)
	}
	
}

export default FetchButton

// esbuild_env/LLFetcher/src/popup/components/FetchButton.vue
<template>
  <div class="btn-group">
    <button :style="{border:(btnState!=1 && btnState!=4?'none':'inherit')}" :disabled="btnState > 1 && btnState < 4" @click="fetchToc()" class="btn btn-sm" :title="'Click to fetch TOC resources ' + toc.title">
      <i class="fa" :class="{'fa-play':btnState==1,'fa-spin fa-spinner':btnState==2,'fa-check':btnState==3,'fa-refresh':btnState==4}"></i>
    </button>

  </div>
</template>
<script lang="ts">
import { defineComponent, ref, PropType } from 'vue';
import {ExerciseFile,Toc} from 'LLFetcher/src/types/lynda';
import Proxy from 'LLFetcher/src/libs/proxy';
// import jQuery from 'jquery';
import {findItems,findDS,getFmt} from 'LLFetcher/src/libs/utils';
import {Toc_tableField} from 'LLFetcher/src/types/tableFields';

export default defineComponent({
  props:{
        toc: {
            required : true,
            type : Object as PropType<Toc_tableField>
        },
        sectionIndex : {
            required : true,
            type : Number
        },
        tocIndex : {
            required : true,
            type : Number
        },
        queue : {
            required : false,
            type : Boolean
        },
        exclude : {
            required : false,
            type : Boolean
        }
  },
    setup(props) {
        const fetchQueueEnabled = ref(props.queue);
        const exclude = ref(props.exclude);
        const toc = ref<Toc_tableField>(props.toc);
        const sectionIndex = ref(props.sectionIndex as number);
        const tocIndex = ref(props.tocIndex as number);
        let exerciseFile  = ref<ExerciseFile>();
        const btnState = ref(1);

        if(exclude.value){
          btnState.value = 3;
        }
        
        return {exclude,toc, sectionIndex, tocIndex, exerciseFile, btnState, fetchQueueEnabled};
    },

    methods:{
      
      fetchToc(){
        
          this.btnState = 2;
          if(this.toc.streamLocationIds.length > 0){
            if(this.fetchQueueEnabled){
                this.btnState = 3;
                console.log('Queue Complete: triggering next fetchToc from parent, lastTocIndex:',this.tocIndex);
                this.$parent.fetchQueueBar.afterProcessQueue(true);
            }
            return;
          }
          const url = this.toc.url;
          Proxy.get(url, (responseText : string)=>{
            let validResource = this.parseToc(responseText);
            if(validResource){
              // 3. set btn state to [checked]
              this.btnState = 3;
              this.$emit('update',{src: 'Popup.CoursePage.TocItem.FetchButton',toc : this.toc, exerciseFile: this.exerciseFile, sectionId:this.toc.sectionId});

                console.log('Queue Complete: triggering next fetchToc from parent, lastTocIndex:',this.tocIndex);
                this.$parent.fetchQueueBar.afterProcessQueue(true);
              
            }else{
              // 3. set btn state to icon [retry]
              this.btnState = 4;
              if(this.fetchQueueEnabled){
                this.$parent.fetchQueueBar.afterProcessQueue(false);
                console.log('Queue Failed: triggering fetchToc from FetchButton, lastTocIndex:',this.tocIndex);
              }
            }
          },(r:any)=>{
            // 3. set btn state to icon [retry]
            this.btnState = 4;
              this.$parent.fetchQueueBar.afterProcessQueue(false);
              console.log('Queue Failed: triggering fetchToc from FetchButton, lastTocIndex:',this.tocIndex);
          });
          
       
      },
      // Rebuild toc data to populate 
      // StreamLocations
      // ExerciseFile
      parseToc(responseText : string){
        let validResource = false;
        const elDiv  = jQuery(`<div>${responseText}</div>`);
        const elCodes = elDiv.find('code');
        let dataCodes = [];
        
        let toc = Object.assign({},this.toc);
        toc.streamLocations = [];
        for(let codeIndex in elCodes){
            let elCode = elCodes[codeIndex];
            try{
                if(elCode.id.match(/^bpr-guid/)){
                    dataCodes.push(JSON.parse(elCode.textContent));
                }
            }catch(e){}
        }
        if(dataCodes.length > 0){
          // console.log(dataCodes);
          const searchTerms = [
              "com.linkedin.learning.api.deco.content.ExerciseFile",
              "com.linkedin.videocontent.Transcript",
              "com.linkedin.videocontent.StreamingLocation"
          ];


          for(let searchTermIdx = 0; searchTermIdx < searchTerms.length; searchTermIdx++){
              const query = searchTerms[searchTermIdx];
              const results = findItems(query, dataCodes);

              if(searchTermIdx == 0){
                // exerciseFile
                try{
                  const exerciseFileObj = findDS('$type','com.linkedin.learning.api.deco.content.ExerciseFile',results,['sizeInBytes','name','url']);
                  this.exerciseFile = exerciseFileObj as ExerciseFile;
                }catch(e){}
              }
              else if(searchTermIdx == 1){
                // transcript
                const transcriptObj = findDS('$type',"com.linkedin.videocontent.Transcript",results,['captionFile','captionFormat']);
                if('object' === typeof transcriptObj){
                  toc.captionUrl = transcriptObj.captionFile;
                  toc.captionFmt = transcriptObj.captionFormat;
                }
              }
              if(searchTermIdx == 2){
                // streamLocations
                const streamLocationObjs = findDS('$type',"com.linkedin.videocontent.StreamingLocation",results,['expiresAt','url'],true);
                if(streamLocationObjs.length > 0 ){
                    for(let stlIdx in streamLocationObjs){
                      const url = streamLocationObjs[stlIdx].url;
                      const fmt = getFmt(url);
                      toc.streamLocations.push({url,fmt})
                  }
                }

              }
          }
        }
        if(toc.captionUrl.length > 0 && toc.streamLocations.length > 0){
          validResource = true; 
          this.toc = toc;
        }
        
        return validResource;
      }
    }
})
</script>
